// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WealthIQ.Infrastructure.Persistence;

#nullable disable

namespace WealthIQ.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WealthIqDbContext))]
    [Migration("20260606194726_DividendAliases")]
    partial class DividendAliases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.AccountRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.BasisInterestRateRow", b =>
                {
                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.HasKey("Year");

                    b.ToTable("BasisInterestRates");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.DataRefreshLogRow", b =>
                {
                    b.Property<string>("Dataset")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastRefreshedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Dataset");

                    b.ToTable("DataRefreshLog");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.DividendAliasRow", b =>
                {
                    b.Property<string>("NormalizedAlias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NormalizedAlias");

                    b.ToTable("DividendAliases");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.FxRateRow", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RateToEur")
                        .HasColumnType("TEXT");

                    b.HasKey("Date", "Currency");

                    b.ToTable("FxRates");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.HistoricalPriceRow", b =>
                {
                    b.Property<string>("ProviderSymbol")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdjustedClose")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProviderSymbol", "Date");

                    b.ToTable("HistoricalPrices");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.ImportBatchRow", b =>
                {
                    b.Property<Guid>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InsertedEntries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedDuplicateEntries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BatchId");

                    b.HasIndex("AccountId");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.ImportDiagnosticRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("ImportDiagnostics");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.InstrumentListingRow", b =>
                {
                    b.Property<string>("Isin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Isin", "Currency");

                    b.ToTable("InstrumentListings");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.InstrumentProfileRow", b =>
                {
                    b.Property<string>("Isin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SubjectToVorabpauschale")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Teilfreistellungsquote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Isin");

                    b.ToTable("InstrumentProfiles");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.InstrumentRow", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISIN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Teilfreistellungsquote")
                        .HasColumnType("TEXT");

                    b.HasKey("InstrumentId");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.PortfolioEntryRow", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRecordReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.HasIndex("SourceSystem", "SourceRecordReference")
                        .IsUnique();

                    b.ToTable("PortfolioEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
