// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WealthIQ.Infrastructure.Persistence;

#nullable disable

namespace WealthIQ.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WealthIqDbContext))]
    partial class WealthIqDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.AccountRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.BasisInterestRateRow", b =>
                {
                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.HasKey("Year");

                    b.ToTable("BasisInterestRates");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.FxRateRow", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RateToEur")
                        .HasColumnType("TEXT");

                    b.HasKey("Date", "Currency");

                    b.ToTable("FxRates");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.ImportBatchRow", b =>
                {
                    b.Property<Guid>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InsertedEntries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedDuplicateEntries")
                        .HasColumnType("INTEGER");

                    b.HasKey("BatchId");

                    b.HasIndex("AccountId");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.ImportDiagnosticRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("ImportDiagnostics");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.InstrumentProfileRow", b =>
                {
                    b.Property<string>("Isin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Teilfreistellungsquote")
                        .HasColumnType("TEXT");

                    b.HasKey("Isin");

                    b.ToTable("InstrumentProfiles");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.InstrumentRow", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISIN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Teilfreistellungsquote")
                        .HasColumnType("TEXT");

                    b.HasKey("InstrumentId");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.PortfolioEntryRow", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRecordReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.HasIndex("SourceSystem", "SourceRecordReference");

                    b.ToTable("PortfolioEntries");
                });

            modelBuilder.Entity("WealthIQ.Infrastructure.Persistence.Rows.YearEndPriceRow", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceEur")
                        .HasColumnType("TEXT");

                    b.HasKey("Year", "Isin");

                    b.ToTable("YearEndPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
